app:
  name: ads
db:
  adapter: postgresql
  host: localhost
  user: postgres
  url: <%= ENV['ADS_DATABASE_URL'] %>
rabbitmq:
  host: <%= ENV['RABBITMQ_HOST'] %>
  username: <%= ENV['RABBITMQ_USER'] %>
  password: <%= ENV['RABBITMQ_PASSWORD'] %>
  consumer_pool: 10
pagination:
  page_size: 10
service:
  auth:
    url: http://localhost:3010/v1
logger:
  path: log/app.log
  level: info
